import sql from '@/app/api/utils/sql';
import { getSession } from '@/utils/session';
import { logAudit } from '@/app/api/utils/audit-logger';

export async function POST(request) {
    try {
        const isStaging = process.env.NODE_ENV === 'staging' || process.env.NODE_ENV === 'development';
        if (!isStaging && process.env.STAGING !== 'true' && process.env.VERCEL_ENV !== 'preview') {
            return Response.json({ error: 'Tool only available in Staging.' }, { status: 403 });
        }
        const session = await getSession(request);

        const body = await request.json();
        const { email } = body; // email of the test company admin

        if (!email) {
            return Response.json({ error: 'Admin email is required.' }, { status: 400 });
        }

        // 1. Fetch the user ID from the admin email
        const users = await sql`SELECT id FROM auth_users WHERE email = ${email}`;
        if (users.length === 0) {
            return Response.json({ error: 'Bedrijf niet gevonden op basis van email.' }, { status: 404 });
        }

        const userId = users[0].id;
        const targetDomainPattern = `%@${userId}.dutygrid-staging.local`;

        // 2. Safe delete based on the specific user ID mapped into the magic "@[id].dutygrid-staging.local" domain used in test data generation
        // This ensures we ONLY delete mock data generated by THIS admin for THIS test company.

        // Delete mock incidents
        await sql`
            DELETE FROM incidents
            WHERE reporting_employee_id IN (
                SELECT id FROM employees WHERE email LIKE ${targetDomainPattern}
            )
        `;

        // Delete mock shifts (and shift_swap_requests automatically cascade)
        await sql`
            DELETE FROM shifts
            WHERE employee_id IN (
                SELECT id FROM employees WHERE email LIKE ${targetDomainPattern}
            )
        `;

        // Delete mock assignments
        await sql`
            DELETE FROM assignments
            WHERE client_id IN (
                SELECT id FROM clients WHERE email LIKE ${targetDomainPattern}
            )
        `;

        // Delete mock clients
        await sql`
            DELETE FROM clients
            WHERE email LIKE ${targetDomainPattern}
        `;

        // Delete mock employees
        const deletedEmployees = await sql`
            DELETE FROM employees 
            WHERE email LIKE ${targetDomainPattern}
            RETURNING id
        `;

        // 3. Delete the Auth Users (Planner & Guard use the staging domain, Admin uses the core email)
        await sql`
            DELETE FROM auth_users
            WHERE email = ${email} OR email LIKE ${targetDomainPattern}
        `;

        // Also clean up any loose references in audit_log
        await sql`
            DELETE FROM audit_logs
            WHERE user_id = ${userId}
        `;

        if (session?.user?.id) {
            await logAudit(
                session,
                'DELETE',
                'staging_environment',
                userId,
                { adminEmail: email, domain: targetDomainPattern },
                null,
                request
            );
        }

        return Response.json({
            success: true,
            message: `Bedrijf en alle accounttoegang succesvol verwijderd. ${deletedEmployees.length} mock medewerkers zijn opgeschoond.`
        });

    } catch (error) {
        console.error('[DeleteCompany API] Error:', error);
        return Response.json({ error: 'Het verwijderen is mislukt vanwege een serverfout.' }, { status: 500 });
    }
}
