import sql from '@/app/api/utils/sql';

export async function POST(request) {
    try {
        const isStaging = process.env.NODE_ENV === 'staging' || process.env.NODE_ENV === 'development';
        if (!isStaging && process.env.STAGING !== 'true' && process.env.VERCEL_ENV !== 'preview') {
            return Response.json({ error: 'Tool only available in Staging.' }, { status: 403 });
        }

        const body = await request.json();
        const { email } = body; // email of the test company admin

        if (!email) {
            return Response.json({ error: 'Admin email is required.' }, { status: 400 });
        }

        // 1. Fetch the tenant_id from the admin email
        const users = await sql`SELECT tenant_id FROM auth_users WHERE email = ${email}`;
        if (users.length === 0) {
            return Response.json({ error: 'Bedrijf niet gevonden op basis van email.' }, { status: 404 });
        }

        const tenantId = users[0].tenant_id;

        // 2. Safe delete based on the magic "@dutygrid-staging.local" domain used in test data generation
        // This ensures we ONLY delete mock data generated by the toolkit, and not real staging test records the user has made manually.

        // Delete mock incidents
        await sql`
            DELETE FROM incidents
            WHERE reporting_employee_id IN (
                SELECT id FROM employees WHERE email LIKE '%@dutygrid-staging.local'
            )
        `;

        // Delete mock shifts (and shift_swap_requests automatically cascade)
        await sql`
            DELETE FROM shifts
            WHERE employee_id IN (
                SELECT id FROM employees WHERE email LIKE '%@dutygrid-staging.local'
            )
        `;

        // Delete mock employees
        const deletedEmployees = await sql`
            DELETE FROM employees 
            WHERE email LIKE '%@dutygrid-staging.local'
            RETURNING id
        `;

        // 3. Reset the Trial clock
        const trialStartsAt = new Date();
        const trialEndsAt = new Date();
        trialEndsAt.setDate(trialEndsAt.getDate() + 14);

        await sql`
            UPDATE companies 
            SET 
                trial_starts_at = ${trialStartsAt.toISOString()},
                subscription_status = 'trialing',
                subscription_plan = 'pro',
                subscription_interval = 'month',
                stripe_customer_id = NULL,
                stripe_subscription_id = NULL,
                current_period_end = NULL
            WHERE id = ${tenantId}
        `;

        return Response.json({
            success: true,
            message: `Bedrijf succesvol gereset. ${deletedEmployees.length} mock medewerkers (en bijbehorende diensten) zijn verwijderd. De proefperiode staat weer op 14 dagen.`
        });

    } catch (error) {
        console.error('[ResetCompany API] Error:', error);
        return Response.json({ error: 'De reset is mislukt vanwege een serverfout.' }, { status: 500 });
    }
}
