import sql from '@/app/api/utils/sql';
import { getSession } from '@/utils/session';
import { logAudit } from '@/app/api/utils/audit-logger';
import { requireStagingEnvironment } from '../guard.js';

export async function POST(request) {
    try {
        requireStagingEnvironment();
        const session = await getSession(request);

        const body = await request.json();
        const { email } = body; // email of the test company admin

        if (!email) {
            return Response.json({ error: 'Admin email is required.' }, { status: 400 });
        }

        // 1. Fetch the user ID from the admin email (DutyGrid uses auth_users ID as the pseudo tenant_id)
        const users = await sql`SELECT id, company_name FROM auth_users WHERE email = ${email}`;
        if (users.length === 0) {
            return Response.json({ error: 'Bedrijf niet gevonden op basis van email.' }, { status: 404 });
        }

        const userId = users[0].id;
        const targetDomainPattern = `%@${userId}.dutygrid-staging.local`;

        // 2. Safe delete based on the specific user ID mapped into the magic "@[id].dutygrid-staging.local" domain used in test data generation
        // This ensures we ONLY delete mock data generated by THIS admin for THIS test company.

        // Delete mock incidents
        await sql`
            DELETE FROM incidents
            WHERE reporting_employee_id IN (
                SELECT id FROM employees WHERE email LIKE ${targetDomainPattern}
            )
        `;

        // Delete mock shifts (and shift_swap_requests automatically cascade)
        await sql`
            DELETE FROM shifts
            WHERE employee_id IN (
                SELECT id FROM employees WHERE email LIKE ${targetDomainPattern}
            )
        `;

        // Delete mock assignments
        await sql`
            DELETE FROM assignments
            WHERE client_id IN (
                SELECT id FROM clients WHERE email LIKE ${targetDomainPattern}
            )
        `;

        // Delete mock clients
        await sql`
            DELETE FROM clients
            WHERE email LIKE ${targetDomainPattern}
        `;

        // Delete mock employees
        const deletedEmployees = await sql`
            DELETE FROM employees 
            WHERE email LIKE ${targetDomainPattern}
            RETURNING id
        `;

        // 3. Reset the Trial clock and subscription status directly on auth_users
        const trialStartsAt = new Date();
        const trialEndsAt = new Date();
        trialEndsAt.setDate(trialEndsAt.getDate() + 14);

        await sql`
            UPDATE auth_users 
            SET 
                trial_starts_at = ${trialStartsAt.toISOString()},
                trial_ends_at = ${trialEndsAt.toISOString()},
                subscription_status = 'trialing',
                stripe_customer_id = NULL,
                stripe_subscription_id = NULL,
                current_period_end = NULL
            WHERE id = ${userId}
        `;

        // 4. Log Audit Event
        if (session?.user?.id) {
            await logAudit(
                session,
                'UPDATE',
                'staging_environment',
                userId,
                null,
                { action: 'reset', targetDomainPattern },
                request
            );
        }

        return Response.json({
            success: true,
            message: `Bedrijf succesvol gereset. ${deletedEmployees.length} mock medewerkers (en bijbehorende diensten) zijn verwijderd. De proefperiode staat weer op 14 dagen.`
        });

    } catch (error) {
        console.error('[ResetCompany API] Error:', error);
        return Response.json({ error: 'De reset is mislukt vanwege een serverfout.' }, { status: 500 });
    }
}
