import sql from '@/app/api/utils/sql';
import { getSession } from '@/utils/session';
import { logAudit } from '@/app/api/utils/audit-logger';
import { requireStagingEnvironment } from '../guard.js';

export async function POST(request) {
    try {
        requireStagingEnvironment();
        const session = await getSession(request);

        // Nuclear Delete - Wipes ALL data globally generated by the staging ecosystem
        const targetDomainPattern = '%@%.dutygrid-staging.local';

        // 1. Find target employee IDs
        const employees = await sql`SELECT id FROM employees WHERE email LIKE ${targetDomainPattern}`;
        const employeeIds = employees.map(e => e.id);

        if (employeeIds.length > 0) {
            // Delete mock incidents
            await sql`DELETE FROM incidents WHERE employee_id = ANY(${employeeIds})`;
            // Delete mock shifts 
            await sql`DELETE FROM shifts WHERE employee_id = ANY(${employeeIds})`;
        }

        // Delete mock assignments
        await sql`
            DELETE FROM assignments
            WHERE client_id IN (
                SELECT id FROM clients WHERE email LIKE ${targetDomainPattern}
            )
        `;

        // Delete mock clients
        await sql`
            DELETE FROM clients WHERE email LIKE ${targetDomainPattern}
        `;

        // Delete mock user_roles to prevent foreign key cascade blocks on auth_users/employees
        await sql`
            DELETE FROM user_roles
            WHERE user_id IN (
                SELECT id::text FROM auth_users WHERE email LIKE ${targetDomainPattern} OR email LIKE 'test+%@dutygrid.test'
            )
        `;

        // Delete mock employees
        const deletedEmployees = await sql`
            DELETE FROM employees 
            WHERE email LIKE ${targetDomainPattern}
            RETURNING id
        `;

        // Delete Auth Users
        const deletedUsers = await sql`
            DELETE FROM auth_users
            WHERE email LIKE ${targetDomainPattern}
               OR email LIKE 'test+%@dutygrid.test'
            RETURNING id
        `;

        // Log Audit Event
        if (session?.user?.id) {
            await logAudit(
                session,
                'DELETE',
                'staging_environment_bulk',
                'NUCLEAR',
                { deletedUsers: deletedUsers.length, domainPattern: targetDomainPattern },
                null,
                request
            );
        }

        return Response.json({
            success: true,
            message: `NUCLEAIRE WIPE UITGEVOERD: ${deletedEmployees.length} mock medewerkers en ${deletedUsers.length} staging-beheerders zijn permanent verwijderd.`
        });

    } catch (error) {
        console.error('[NukeCompanies API] Error:', error);
        return Response.json({ error: 'Nucleaire wipe is gecrasht vanwege een serverfout.' }, { status: 500 });
    }
}
