import sql from '@/app/api/utils/sql';
import { getSession } from '@/utils/session';
import { logAudit } from '@/app/api/utils/audit-logger';
import { requireStagingEnvironment } from '../guard.js';

export async function POST(request) {
    try {
        requireStagingEnvironment();
        const session = await getSession(request);

        // Nuclear Delete - Wipes ALL data globally generated by the staging ecosystem
        // Using company_name ILIKE 'Test %' catches BOTH new and legacy mock generated companies

        // 0. Sweep strict NO ACTION user foreign-key constraints
        const testUsers = await sql`
            SELECT id, email 
            FROM auth_users 
            WHERE email LIKE '%@%.dutygrid-staging.local' 
               OR email LIKE 'test+%@dutygrid.test'
               OR company_name ILIKE 'Test %'
        `;
        const testUserIds = testUsers.map(u => String(u.id));
        const testEmails = testUsers.map(u => u.email);

        if (testUserIds.length > 0) {
            await sql`DELETE FROM shifts WHERE created_by = ANY(${testUserIds})`;
            await sql`DELETE FROM shift_swap_requests WHERE approved_by_user_id = ANY(${testUserIds})`;
        }

        if (testEmails.length > 0) {
            // 1. Find target employee IDs
            const employees = await sql`
                SELECT id FROM employees 
                WHERE email = ANY(${testEmails})
                   OR email LIKE '%@%.dutygrid-staging.local'
            `;
            const employeeIds = employees.map(e => e.id);

            if (employeeIds.length > 0) {
                // Delete mock incidents
                await sql`DELETE FROM incidents WHERE employee_id = ANY(${employeeIds})`;
                // Delete mock shifts 
                await sql`DELETE FROM shifts WHERE employee_id = ANY(${employeeIds})`;
            }

            // 2. Delete mock assignments based on internal clients (which share the same emails roughly)
            await sql`
                DELETE FROM assignments
                WHERE client_id IN (
                    SELECT id FROM clients 
                    WHERE email = ANY(${testEmails}) 
                       OR email LIKE '%@%.dutygrid-staging.local'
                )
            `;

            // Delete mock clients
            await sql`
                DELETE FROM clients 
                WHERE email = ANY(${testEmails}) 
                   OR email LIKE '%@%.dutygrid-staging.local'
            `;
        }

        // Delete mock user_roles to prevent foreign key cascade blocks on auth_users/employees
        if (testUserIds.length > 0) {
            await sql`DELETE FROM user_roles WHERE user_id = ANY(${testUserIds})`;
        }

        // Delete mock employees
        let deletedEmployees = [];
        if (testEmails.length > 0) {
            deletedEmployees = await sql`
                DELETE FROM employees 
                WHERE email = ANY(${testEmails})
                   OR email LIKE '%@%.dutygrid-staging.local'
                RETURNING id
            `;
        }

        // Delete Auth Users
        const deletedUsers = await sql`
            DELETE FROM auth_users
            WHERE email LIKE '%@%.dutygrid-staging.local'
               OR email LIKE 'test+%@dutygrid.test'
               OR company_name ILIKE 'Test %'
            RETURNING id
        `;

        // Log Audit Event
        if (session?.user?.id) {
            await logAudit(
                session,
                'DELETE',
                'staging_environment_bulk',
                'NUCLEAR',
                { deletedUsers: deletedUsers.length, domainPattern: targetDomainPattern },
                null,
                request
            );
        }

        return Response.json({
            success: true,
            message: `NUCLEAIRE WIPE UITGEVOERD: ${deletedEmployees.length} mock medewerkers en ${deletedUsers.length} staging-beheerders zijn permanent verwijderd.`
        });

    } catch (error) {
        console.error('[NukeCompanies API] Error:', error);
        return Response.json({ error: 'Nucleaire wipe is gecrasht vanwege een serverfout.' }, { status: 500 });
    }
}
