import sql from '@/app/api/utils/sql';
import { getSession } from '@/utils/session';
import { logAudit } from '@/app/api/utils/audit-logger';

export async function POST(request) {
    try {
        const isStaging = process.env.NODE_ENV === 'staging' || process.env.NODE_ENV === 'development';
        if (!isStaging && process.env.STAGING !== 'true' && process.env.VERCEL_ENV !== 'preview') {
            return Response.json({ error: 'Tool only available in Staging.' }, { status: 403 });
        }
        const session = await getSession(request);

        // Nuclear Delete - Wipes ALL data globally generated by the staging ecosystem
        const targetDomainPattern = '%@%.dutygrid-staging.local';

        // Delete mock incidents
        await sql`
            DELETE FROM incidents
            WHERE reporting_employee_id IN (
                SELECT id FROM employees WHERE email LIKE ${targetDomainPattern}
            )
        `;

        // Delete mock shifts 
        await sql`
            DELETE FROM shifts
            WHERE employee_id IN (
                SELECT id FROM employees WHERE email LIKE ${targetDomainPattern}
            )
        `;

        // Delete mock assignments
        await sql`
            DELETE FROM assignments
            WHERE client_id IN (
                SELECT id FROM clients WHERE email LIKE ${targetDomainPattern}
            )
        `;

        // Delete mock clients
        await sql`
            DELETE FROM clients
            WHERE email LIKE ${targetDomainPattern}
        `;

        // Delete mock employees
        const deletedEmployees = await sql`
            DELETE FROM employees 
            WHERE email LIKE ${targetDomainPattern}
            RETURNING id
        `;

        // Delete Auth Users (This deletes all planner/guard permutations and any test admin using dutygrid.test patterns)
        const deletedUsers = await sql`
            DELETE FROM auth_users
            WHERE email LIKE ${targetDomainPattern}
               OR email LIKE 'test+%@dutygrid.test'
            RETURNING id
        `;

        // Log Audit Event
        if (session?.user?.id) {
            await logAudit(
                session,
                'DELETE',
                'staging_environment_bulk',
                'NUCLEAR',
                { deletedUsers: deletedUsers.length, domainPattern: targetDomainPattern },
                null,
                request
            );
        }

        return Response.json({
            success: true,
            message: `NUCLEAIRE WIPE UITGEVOERD: ${deletedEmployees.length} mock medewerkers en ${deletedUsers.length} staging-beheerders zijn permanent verwijderd.`
        });

    } catch (error) {
        console.error('[NukeCompanies API] Error:', error);
        return Response.json({ error: 'Nucleaire wipe is gecrasht vanwege een serverfout.' }, { status: 500 });
    }
}
